### ISSUE TITLE
When turning on the Advanced Resource Template one can't link annotations to Omeka Resources

### ISSUE THREAD

**Issue by sinanatra** [Daniel-KM/Omeka-S-module-AdvancedResourceTemplate#3]
When turning on the Advanced Resource Template (v. 3.3.4.15.2), the annotation features works partially. Omeka resources cannot be linked anymore, only literals. Nevertheless, when disabling the template, everything works.

**Comment by Daniel-KM** [comment]
It is fixed in 3.3.4.16.

**Comment by sinanatra** [comment]
thanks! when would you release that specific version, so that i could test it?

**Comment by sinanatra** [comment]
actually, i just tested 3.3.4.16 and the issue still occurs. When linking an Omeka Resource, i see the annotation added, but not the item linked.
